<?xml version="1.0"?>
<?xml-model href="http://ros.org" schematypens="http://w3.org"?>
<package format="3">
  <name>vision</name>
  <version>0.0.0</version>
  <description>package responsible for distance estimation</description>
  <maintainer email="borisaushev.com@gmail.com">bossb</maintainer>
  <license>Apache-2.0</license>

  <!-- Оставляем только системный ROS 2 стек -->
  <depend>rclpy</depend>
  <depend>std_srvs</depend>
  <depend>rclcpp</depend>
  
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>sensor_msgs_py</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
